### ISSUE TITLE
scripts.php

### ISSUE THREAD

**Issue by Aditerum** [wpexplorer/wpex-tetris#1]
The free TETRIS theme has an issue in the inc/scripts.php code for the use of Google fonts when used on HTTPS. I have made a manual edit to this file so that the 8 calls to insecure url: http://fonts.gstatic.com are avoided.

**Comment by wpexplorer** [comment]
@Aditerum Thanks for letting me know, I'll push out an update in a bit ;)

**Comment by wpexplorer** [comment]
Just pushed out the update with a few other small tweaks to clean up some code.

**Comment by Aditerum** [comment]
Update failed - download forbidden.

**Comment by wpexplorer** [comment]
@Aditerum Should be fixed now, thanks for the heads up!

ps: Feel free to push any pull-request you'd like in the future for updates if you find any other bug, want to make an enhancement or other.
